apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: khaboss/flask:latest
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-clusterip-srv
spec:
  selector:
    app: flask
  ports:
    - name: flask
      protocol: TCP
      port: 80
      targetPort: 80