version: '2'
services:
  flask:
    image: khaboss/flask
    ports:
      - "5000:80"
    restart: always

  postgres-srv:
    image: khaboss/postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=kjaglsjf
      - POSTGRES_USER=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always

  redis-srv:
    image: khaboss/redis
    ports:
      - "6379:6379"
    restart: always