FROM alpine

# basic flask environment
RUN apk add --no-cache bash git gcc nginx uwsgi uwsgi-python3 cmd:pip3 \
	&& pip3 install --upgrade pip \
	&& pip3 install flask

####################
####################
# application folder
ARG CURRENT_ENV=dev

ENV APP_DIR /app
ENV APP_PORT 80
ENV CURRENT_ENV $CURRENT_ENV

####################
####################
# app dir
RUN mkdir ${APP_DIR} \
	&& chown -R nginx:nginx ${APP_DIR} \
	&& chmod 777 /run/ -R \
	&& chmod 777 /root/ -R
VOLUME ${APP_DIR}
WORKDIR ${APP_DIR}

# expose web server port
# only http, for ssl use reverse proxy
EXPOSE ${APP_PORT}

# copy config files into filesystem
COPY nginx.conf /etc/nginx/nginx.conf
COPY app.ini /app.ini
COPY entrypoint.sh /entrypoint.sh

# exectute start up script
ENTRYPOINT ["/entrypoint.sh"]

COPY app/ .

RUN pip install -r requirements.txt

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]